version: '3.7'
services:
  web:
    image: pro-disciplina-web:dev
    container_name: pro-disciplina-web-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/app/src'
    ports:
      - '80'
    env_file:
      - .env
